version: '3'


services:
  registro:
    build: ./registro
    depends_on:
      - dataregistros
    environment:
      - PORT=2500
      - MONGODB_CNN=mongodb://dataregistros:27017/test
  palabra:
    build: ./palabra
    depends_on:
      - datapalabras
    environment:
      - PORT=2500
      - MONGODB_CNN=mongodb://datapalabras:27017/test
  idioma:
    build: ./idioma
    depends_on:
      - dataidiomas
    environment:
      - PORT=2500
      - MONGODB_CNN=mongodb://dataidiomas:27017/test
  dataregistros:
    image: mongo
    # ports:
    #   - "27017:27017"
  datapalabras:
    image: mongo
    # ports:
    #   - "27017:27017"
  dataidiomas:
    image: mongo
    # ports:
    #   - "27017:27017"
  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - registro
      - palabra
      - idioma